import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import { useCart } from 'react-use-cart';
import { useIsClient } from 'usehooks-ts';

import s from './page.module.scss';

export async function getServerSideProps() {
  const { data } = await axios.get(
    'https://riot1806.pythonanywhere.com/products/'
  );
  return { props: { data } };
}

const SingleProduct = ({ data }) => {
  const { getItem, addItem, removeItem } = useCart();
  const isClient = useIsClient();
  const router = useRouter();
  const findProduct = data?.find((el) => {
    return el?.id == router.query.id;
  });
  return (
    <>
      <Head>
        <title>
          {findProduct?.name} - Morgan&#039;s &#8212; Официальный сайт мужской
          косметики Morgan&#039;s в Узбекистане
        </title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel="icon" href="/favicon.ico" /> */}

        <link
          rel='icon'
          href='https://morgans.kz/wp-content/uploads/2022/06/cropped-morgans-ico-32x32.png'
          sizes='32x32'
        />
        <link
          rel='icon'
          href='https://morgans.kz/wp-content/uploads/2022/06/cropped-morgans-ico-192x192.png'
          sizes='192x192'
        />
        <link
          rel='apple-touch-icon'
          href='https://morgans.kz/wp-content/uploads/2022/06/cropped-morgans-ico-180x180.png'
        />
        <meta
          name='msapplication-TileImage'
          content='https://morgans.kz/wp-content/uploads/2022/06/cropped-morgans-ico-270x270.png'
        />

        <meta property='og:locale' content='ru_RU' />
        <meta property='og:site_name' content='Morgan&#039;s' />
        <meta property='og:title' content={findProduct?.name} />
        <meta property='og:url' content='https://morgans.uz' />
        <meta property='og:type' content='website' />
        <meta property='og:description' content={findProduct?.desc} />
        <meta property='og:image' content={findProduct?.image} />
        <meta property='og:image:url' content={findProduct?.image} />
        <meta property='og:image:secure_url' content={findProduct?.image} />
        {/* <meta property="article:publisher" content="https://www.facebook.com/morganskazakhstan" /> */}
        <meta name='twitter:title' content={findProduct?.name} />
        <meta name='twitter:url' content='https://morgans.uz' />
        <meta name='twitter:description' content={findProduct?.name} />
        <meta name='twitter:image' content={findProduct?.image} />
        <meta name='twitter:card' content='summary_large_image' />
      </Head>
      <div>
        <section className={s.page}>
          <div className='container'>
            <div className={s.wrapper}>
              <img
                className={s.img}
                src={findProduct?.image}
                alt={findProduct?.description}
              />

              <div className={s.box}>

            

                
                <h6>В наличии: {findProduct?.quantity}</h6>
                <h1>{findProduct?.name}</h1>
                <h2>{findProduct?.description}</h2>
                <p>
                  {findProduct?.price} <span>$</span>
                </p>
                <b>{findProduct?.wvq}</b>


                {findProduct?.quantity >= 1 ? (
                  isClient && !getItem(findProduct?.id) ? (
                    <button
                      className='btn'
                      onClick={() => addItem(findProduct)}
                    >
                      В корзину
                    </button>
                  ) : (
                    <button
                      className='btn'
                      onClick={() => removeItem(findProduct?.id)}
                    >
                      Отменить
                    </button>
                  )
                ) : (
                  <span className={s.single_nope}>Нет в наличии</span>
                )}
                
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export default SingleProduct;
